# Site settings
title: "Akshit Arora"
email: akshit.arora@colorado.edu
description: "Artificial Intelligence, Deep Learning and Photography"
baseurl: ""
url: "https://aroraakshit.github.io/"
title_description: "Graduate student at the <a href=\"https://www.colorado.edu/\">University of Colorado Boulder</a><br>Currently interested in Deep Learning, Cognitive Science and Artificial Intelligence.<br><a href=\"https://akshitarora.github.io/about/\">About Me</a> | <a href=\"akshit_cv.pdf\">Resume</a> | <a href=\"mailto:akshit.arora@colorado.edu\">Email Me</a>"
title_image: "akshit.JPG"
google_analytics: "UA-109066326-1"
disqus_account: akshitarora-github-io
github_repository: https://github.com/aroraakshit/carte-noire
addthis_id: ra-59f92e11f7baa2ae
post_limit: 5
author_name: "Akshit Arora"

# Social usernames/URLs
twitter_username: AkshitArora1995
github_username:  aroraakshit
instagram_username: akshit1995
reddit_username: 
linkedin_link: https://www.linkedin.com/in/akshitarora1995/
google_plus_link:
stackoverflow_link: 
xing_link:
facebook_link: 

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a> and modified by <a href=\"https://twitter.com/AkshitArora1995\">Akshit</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/aroraakshit/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
